fix(incl): discard string contexts of potential store paths
- during preprocessing, we need to discard the string contexts
  of potential store paths since store paths are forbidden here, e.g.:

```
error: the string 'custom-environment-variables.json' is not allowed to refer to a store path (such as '/nix/store/mwn68zz4zfnbgn4qybn4hvfngp3f8dha-source')

       at /nix/store/f5bdfk3w5i3riprpd1wrw03nyzjmj1j4-source/lib/sources.nix:26:20:

           25|   */
           26|   pathType = path: getAttr (baseNameOf path) (readDir (dirOf path));
             |                    ^
           27|

       … while evaluating 'pathType'

       at /nix/store/f5bdfk3w5i3riprpd1wrw03nyzjmj1j4-source/lib/sources.nix:26:14:

           25|   */
           26|   pathType = path: getAttr (baseNameOf path) (readDir (dirOf path));
             |              ^
           27|

       … from call site

       at /nix/store/f5bdfk3w5i3riprpd1wrw03nyzjmj1j4-source/lib/sources.nix:31:52:

           30|   */
           31|   pathIsDirectory = path: if pathExists path then (pathType path) == "directory" else false;
             |                                                    ^
           32|

       … while evaluating 'pathIsDirectory'

       at /nix/store/f5bdfk3w5i3riprpd1wrw03nyzjmj1j4-source/lib/sources.nix:31:21:

           30|   */
           31|   pathIsDirectory = path: if pathExists path then (pathType path) == "directory" else false;
             |                     ^
           32|

       … from call site

       at /nix/store/fz4wgaifalijf9vmr7da7pcdz5risvmy-source/incl.nix:13:13:

           12|       sum: verified:
           13|         if (lib.pathIsDirectory (toString verified))
             |             ^
           14|         then {

       … while evaluating anonymous lambda
```